# Generated by Django 4.1.3 on 2022-12-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ("-list_date",)},
        ),
    ]
