# Generated by Django 4.1.3 on 2022-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="realtor",
            options={"ordering": ("-hire_date",)},
        ),
        migrations.AlterField(
            model_name="realtor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
